### PR TITLE
Add support for updating wps_subtitle rest field via Rest API

### PR DESCRIPTION
**Pull request by chriselkins**
I've tested this and am using it to import posts with subtitles into one of my sites via the Rest API.

I'm using https://github.com/robbiet480/go-wordpress in one of my projects along with this change in your plugin to automate the imports.

### CODE REVIEW

**Comment by benhuson** [comment]
Thanks Chris.

I'm just searching to find out if the `update_rest_field()` method needs to have any sanitization or permission checks, or wether the REST API takes care of that. AT the moment I have;t been able to find a definitive answer.

**Comment by chriselkins** [comment]
I believe update_item_permissions_check() in wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php handles the permissions checking. It only allows the rest field to be updated if the user has permissions to the post. That makes sense here and what's desired in this case; the subtitle should be updated only if the user can edit the post that the subtitle is part of.

Here's the call chain for that. That function in turn allows update_item() in the same file to be called, which then in turn calls update_additional_fields_for_object() in wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php and class-wp-rest-controller.php, which finally calls update_callback in your plugin only if the field exists in the rest call. 

As for sanitizing, I followed the lead on what you're doing in plugin/admin/admin.php _save_post() which is updating the post meta field if ( isset( $_POST['wps_subtitle'] ) ). It allows things like <script>alert('hi')</script>. Maybe this should change too? At convert the subtitle string with htmlentities()?

It wouldn't be a bad idea though to at least ensure the value is a valid string in both _save_post() and in the rest update callback. I'm not sure if stripping any content, other than maybe invalid UTF-8 and trimming whitespace, would be a good idea though. Instead of stripping to sanitize, how about htmlentities($str, ENT_QUOTES, "UTF-8")?

**Comment by benhuson** [comment]
Thanks for the clarification on permissions :)

Regarding sanitization, I know from forum posts that some users are including HTML tags such as `<strong>` and `<em>`  in the subtitle field so `htmlentities()` sanitisation not a good idea.

Perhaps using `wp_kses_post()` for REST updates and in `_save_post()` just to strip out scripts etc but allow HTML would be safest?

**Comment by chriselkins** [comment]
I think wp_kses_post() does make the most sense. I've committed the change to both _save_post and the rest update to apply wp_kses_post(). I tested on my site and all seems well. Tags like <strong> and <em> are allowed and not stripped while <script> tags are stripped. Let me know what you think of this. Thanks!

**Comment by benhuson** [comment]
Excellent!
I'll check if I have any other updates pending and merge these in with them to the next release.

Thanks @chriselkins

**Comment by benhuson** [comment]
This has been merged and is in version 3.4

https://github.com/benhuson/wp-subtitle/commit/11cc9f19ec778e41776afe2ecfeecde9014c7c28
https://github.com/benhuson/wp-subtitle/commit/7373123f36982929d885abdb8eeb10e4dd911bb5

**Pull request closed without merging**
